fix #117: Skip payment gate when not needed
bratislava/paas-mpa pull request #209
Opened 2023-11-28 14:11 UTC by radoslavzeman

- redirect directly to confirmation screen on purchases that are zero price (NPK, BPK)
- add translations keys for missing errors - TODO translations
- reorganize components in purchase screen
  - move Pay button to main purchase screen
  - keep only additional details in PurchaseBottomSheet
  - create `PurchaseSummaryRow` and `PurchaseErrorPanel` to separate components
- check pricing api error to display `PurchaseErrorPanel` only for code 422 and `errorName` that matcher pricing api error

2023-11-28 15:41 UTC, PavelFilo requested changes

2023-11-28 15:41 UTC, PavelFilo commented on components/tickets/PurchaseBottomSheet.tsx
> +              {priceData.tax == null ? null : (
what about `typeof priceData.tax === 'number'`?

2023-11-28 15:41 UTC, PavelFilo commented on utils/errorPricingApi.ts
> +  errorName: PRICINGAPIERROR
I know that this type is generated, but it looks awful. Is there any way to change it somewhere?

2023-11-28 15:41 UTC, PavelFilo commented on components/purchase/PurchaseErrorPanel.tsx
> +    priceQuery.error.response &&
I would remove this line and add `?` to next one `priceQuery.error.response?.status === 422 &&`

2023-11-29 08:45 UTC, radoslavzeman commented on components/tickets/PurchaseBottomSheet.tsx
> +              {priceData.tax == null ? null : (
Using `isDefined` instead.

2023-11-29 09:01 UTC, PavelFilo approved these changes

2023-11-29 09:11 UTC, merged