#510, #515, #516, #518: Update translations, Fix feedback text input, Remove map rotation
bratislava/paas-mpa pull request #525
Opened 2024-06-04 14:55 UTC by radoslavzeman

2024-06-04 19:23 UTC, PavelFilo requested changes

2024-06-04 19:23 UTC, PavelFilo commented on components/map/Map.tsx
remove everything that was used for rotation... cameraHeading state, mapHeading state, rotateToNorth and also check if everything inside useCameraChangeHandler is used (remove if not)

2024-06-05 06:07 UTC, radoslavzeman commented on components/map/Map.tsx
Thank you for the comment, remaining old code has been removed :) ✅

2024-06-05 06:07 UTC, radoslavzeman commented on components/map/CompassButton.tsx
> -  const { rotateToNorth } = useMapStoreContext()
✅

2024-06-05 06:41 UTC, PavelFilo approved these changes
good job

2024-06-05 06:55 UTC, merged