702 Captcha second stage integration
bratislava/paas-mpa pull request #708
Opened 2024-12-09 15:52 UTC by PavelFilo

The second stage includes two tries and then the signup.
We found some of the captcha verifications fail (10 in 5 days) so we want to know whether they will fail on second try, because turnstile docs suggest to retry the captcha on errors like those.

PR includes
- add retry to captcha after one failed one,
- add error message so user knows what is happening

2024-12-10 13:24 UTC, MarekBodingerBA commented
It's a bit hard follow captcha logic (retry, rerender and so on) and I think it shouldn't be leaking to the sign in page. You can add `wasRetried` flag and act upon it. Also using the `key` to trigger a rerender is common practise that you can use.

Something like this: https://chatkit.app/s/kgguym0iupue800

2024-12-10 13:26 UTC, MarekBodingerBA requested changes
.

2024-12-19 05:37 UTC, radoslavzeman approved these changes
Tell me if you can merge with this approval or not :)

2024-12-19 05:37 UTC, radoslavzeman commented on app/(auth)/sign-in/index.tsx
Please doublecheck if change from `phoneWithoutSpaces` to `phone` is 100% correct. I see the issue issue and TODO comment with `phoneWithoutSpaces`. But `phone` can contain spaces - please double-check, if this will not cause problems.

2024-12-20 08:05 UTC, merged